apiVersion: v1
kind: Service
metadata:
  name: laughing-website
  labels:
    app: laughing-website

spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: laughing-website
    
---    
   
apiVersion: v1
kind: ReplicationController
metadata:
  name: laughing-website-v1
spec:
  replicas: 3
  selector:
    app: laughing-website
    ver: 1-0
    
  template:
    metadata:
      labels:
        app: laughing-website
        ver: 1-0
    spec:
      containers:
      - name: nginx
        image: ckleban/nginx-from-git:v2
        livenessProbe:
          # an http probe
          httpGet:
            path: /
            port: 80
          # length of time to wait for a pod to initialize
          # after pod startup, before applying health checking
          initialDelaySeconds: 3
          timeoutSeconds: 1    
          
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /wwwdata
          name: gitdata
      volumes:
      - name: gitdata
        gitRepo:
          repository: https://github.com/ckleban/funny-baby-website
          revision:  c439c1b3f702a3b167180d17ddcf5f6786c7feb3
          
          
          
