---    
   
apiVersion: v1
kind: ReplicationController
metadata:
  name: static-website-v3-bad
spec:
  replicas: 1
  selector:
    app: website-from-git
    ver: 3-0
    
  template:
    metadata:
      labels:
        app: website-from-git
        ver: 3-0
        run: nginx
    spec:
      containers:
      - name: nginx
        image: ckleban/nginx-from-git:v2
        livenessProbe:
          # an http probe
          httpGet:
            path: /
            port: 80
          # length of time to wait for a pod to initialize
          # after pod startup, before applying health checking
          initialDelaySeconds: 3
          timeoutSeconds: 1    
          
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "256Mi"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /wwwdata
          name: gitdata
      volumes:
      - name: gitdata
        gitRepo:
          repository: https://github.com/ckleban/sample-website
          revision: 5a953a5bec6e34a1f3f36a845a36bd90ce4db7aaXXX
          